### ISSUE TITLE
Folder deletion under Windows doesn't work

### ISSUE THREAD

**Issue by troynt** [fusic/filebinder#1]
In the bindable behavior, I changed recursiveRemoveDir to the following, and it worked as expected.
function recursiveRemoveDir($dir) {
  uses('folder');
  $folder = &new Folder($dir);
  @$folder->delete($folder->pwd());
}

**Comment by k1LoW** [comment]
Hello troynt.

Thank you for your comment.
and I fix some code.

But I don't have PHP on Windows.
Could you check it yourself?

Thanks.

**Comment by troynt** [comment]
It works as expected.
